version: '3.8'

services:
  esr:
    build:
      context: ./esr
      dockerfile: Dockerfile
    ports:
      - "20102:20102"
    networks:
      - backend

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "20103:20103"
    networks:
      - backend

networks:
  backend:
    driver: bridge
