services:
  influxdb:
    container_name: influxdb
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  esr:
    container_name: esr
    depends_on: 
      - influxdb
    build:
      context: ./esr
      dockerfile: Dockerfile
    ports:
      - "20102:20102"
    networks:
      - backend

  orchestrator:
    container_name: orch
    depends_on: 
      - influxdb
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "20103:20103"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  influxdb2-data:
  influxdb2-config:
